name: phaseout
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # Background execution
  flutter_background_service: ^5.0.5

  # Device monitoring
  battery_plus: ^6.0.1
  app_usage: ^4.1.0
  wakelock_plus: ^1.2.8

  # Notifications
  flutter_local_notifications: ^17.2.2

  # ML
  tflite_flutter: ^0.10.4

  # Storage
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  drift: ^2.18.0

  # Permissions
  permission_handler: ^11.3.1

  # Networking (NLP calls)
  dio: ^5.6.0

  # Secure storage (API keys)
  flutter_secure_storage: ^9.2.2

  # Animations
  lottie: ^3.1.2

  # Path utilities
  path: ^1.9.0

  # Firebase
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.1
  firebase_analytics: ^11.3.1
  firebase_auth: ^5.2.1
  
  url_launcher: any
  cloud_firestore: any
  package_info_plus: any
  device_apps: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11    
  drift_dev: ^2.18.0

flutter:

  uses-material-design: true
