// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_2Kx3b0fZJTpwHBUdXxifsFSYLtosUE',
    appId: '1:665766320525:web:06e05781e0681ba56245c4',
    messagingSenderId: '665766320525',
    projectId: 'phaseout-dev',
    authDomain: 'phaseout-dev.firebaseapp.com',
    storageBucket: 'phaseout-dev.firebasestorage.app',
    measurementId: 'G-N609CNE54T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GM_VyZ8GbWo_X1_PEwAIpPIU5sdiRos',
    appId: '1:665766320525:android:2cf6e79dd7f645eb6245c4',
    messagingSenderId: '665766320525',
    projectId: 'phaseout-dev',
    storageBucket: 'phaseout-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbpbbB-cHeHFbAeS3k3Dpp5t64YCcDEg',
    appId: '1:665766320525:ios:5fe0ca7cfbbe4f7c6245c4',
    messagingSenderId: '665766320525',
    projectId: 'phaseout-dev',
    storageBucket: 'phaseout-dev.firebasestorage.app',
    iosBundleId: 'com.example.phaseout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbpbbB-cHeHFbAeS3k3Dpp5t64YCcDEg',
    appId: '1:665766320525:ios:5fe0ca7cfbbe4f7c6245c4',
    messagingSenderId: '665766320525',
    projectId: 'phaseout-dev',
    storageBucket: 'phaseout-dev.firebasestorage.app',
    iosBundleId: 'com.example.phaseout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4_2Kx3b0fZJTpwHBUdXxifsFSYLtosUE',
    appId: '1:665766320525:web:678ecf7b89d050686245c4',
    messagingSenderId: '665766320525',
    projectId: 'phaseout-dev',
    authDomain: 'phaseout-dev.firebaseapp.com',
    storageBucket: 'phaseout-dev.firebasestorage.app',
    measurementId: 'G-90G18GJLCS',
  );
}
